baseURL = "https://griffin-wirth.netlify.app"
title = "All About Me"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<Griffin>"
description = "Griffin's Portfolio"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/Wirth.jpg"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Griffin Wirth"
subtitle = "Integrative Informatics"
imageUrl = "Wirth.jpg"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "tags"
url = "/tags/"

[[params.profileMode.buttons]]
name = "puppies"
url = "https://google.com/search?tbm=isch&q=puppies"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/WirthG"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/"

[[menu.main]]
identifier = "About Me"
name = "blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "link"
name = "A link"
url = "https://google.com/search?tbm=isch&q=cute%20puppies"
weight = 30
